# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Microsoft Partner Network(f157d68d-6c7b-497d-882c-7173549d4add)'
    backendAzureRmResourceGroupName: 'Non-TF'
    backendAzureRmStorageAccountName: 'architechstfstatefiles'
    backendAzureRmContainerName: 'aztransittfstate'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Microsoft Partner Network(f157d68d-6c7b-497d-882c-7173549d4add)'

- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Microsoft Partner Network(f157d68d-6c7b-497d-882c-7173549d4add)'


